#!/bin/sh
#
# chef-client for rc.d usage
# $Id$

# PROVIDE: chef_server_webui
# REQUIRE: DAEMON chef_server
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable chef-server-webui
#
#  chef_server_webui_enable="YES"


. "/etc/rc.subr"

name="chef_server_webui"
rcvar=`set_rcvar`
load_rc_config $name

: ${chef_server_webui_enable="NO"}
: ${chef_server_webui_configfile="/usr/local/etc/chef/server.rb"}

if [ -n "$chef_server_webui_listen" ]
	then
		listen="-h ${chef_server_webui_listen}"
	else
		listen=""
fi

pidfile="/var/run/chef-server-webui.pid"
command="/usr/local/bin/chef-server-webui"
procname="ruby18"
chef_server_webui_flags=" --pid ${pidfile} -n chef-server-webui -e production  ${chef_server_webui_listen}-d -C ${chef_server_webui_configfile}"

load_rc_config $name
run_rc_command "$1"
